version: '3.6'

services:
  db:
    image:  mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: dummypassword
    ports:
      - 3306:3306

  #adminer:
  #  image: adminer
  #  restart: always
  #    ports:
  #      - 8080:8080